services:
  vllmapp:
    image: vllmapp:latest
    pull_policy: never
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    volumes:
      - /home/spark1/vllmapp-data:/data
    expose:
      - "8080"
